### Numpy
- convert a list,tuple,dict into numpy array
- how to generate array with in arange of values
    - arange
    - linspace
    - random,randint
- basic arthimatic operators on numpy array

In [1]:
import numpy as np
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# how to slicing
print(a[1:10])
print(a[1:5:2])
print(a[:])

[1 2 3 4 5 6 7 8 9]
[1 3]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [7]:
# fancy indexing or boolean indexing
print(a[a>5])

[6 7 8 9]


In [8]:
a.shape

(10,)

In [9]:
a.ndim # how many dimensions in array

1

In [11]:
a2=np.random.randint(10,30,(3,3))
a2

array([[11, 14, 26],
       [11, 22, 12],
       [24, 21, 16]])

In [13]:
print(a2.ndim)
print(a2.shape)

2
(3, 3)


In [16]:
for i in a2:
    for j in i:
        print(j,end=" ")
    print()

11 14 26 
11 22 12 
24 21 16 


In [19]:
print(a2[0],type(a2[0]),a2[0].shape)

[11 14 26] <class 'numpy.ndarray'> (3,)


In [20]:
print(a2[1:],type(a2[1:]),a2[1:].shape)

[[11 22 12]
 [24 21 16]] <class 'numpy.ndarray'> (2, 3)


In [33]:
# rows from 0 to 2
# columns from 0 to 2
# 1st row and second column
print(a2[1][2])
print(a2[1,2])

12
12


In [35]:
print(a2[1:3,0:2])

[[11 22]
 [24 21]]


In [36]:
print(a2)

[[11 14 26]
 [11 22 12]
 [24 21 16]]


In [37]:
a3=np.random.randint(10,100,(5,5,3))
a3

array([[[18, 92, 95],
        [15, 92, 59],
        [52, 50, 21],
        [52, 13, 28],
        [93, 10, 54]],

       [[30, 67, 94],
        [99, 82, 93],
        [58, 46, 63],
        [50, 34, 31],
        [45, 55, 76]],

       [[74, 75, 82],
        [77, 78, 77],
        [34, 12, 85],
        [19, 19, 59],
        [85, 67, 59]],

       [[93, 47, 91],
        [85, 31, 11],
        [42, 95, 25],
        [24, 33, 82],
        [86, 27, 41]],

       [[97, 68, 31],
        [74, 29, 88],
        [29, 79, 33],
        [92, 82, 98],
        [68, 48, 56]]])

In [38]:
print(a3[:2]) # indices - 0,1

[[[18 92 95]
  [15 92 59]
  [52 50 21]
  [52 13 28]
  [93 10 54]]

 [[30 67 94]
  [99 82 93]
  [58 46 63]
  [50 34 31]
  [45 55 76]]]


In [39]:
print(a3[1::2])

[[[30 67 94]
  [99 82 93]
  [58 46 63]
  [50 34 31]
  [45 55 76]]

 [[93 47 91]
  [85 31 11]
  [42 95 25]
  [24 33 82]
  [86 27 41]]]


In [40]:
print(a3[1::2,2])

[[58 46 63]
 [42 95 25]]


In [41]:
print(a3[1::2,0:5:2])

[[[30 67 94]
  [58 46 63]
  [45 55 76]]

 [[93 47 91]
  [42 95 25]
  [86 27 41]]]


In [43]:
print(a3[1::2,0:5:2,0])

[[30 58 45]
 [93 42 86]]


In [44]:
a3==86

array([[[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [ True, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]]])

In [45]:
# boolean indexing
a3[a3==86]

array([86])

In [46]:
a3[a3>50]

array([92, 95, 92, 59, 52, 52, 93, 54, 67, 94, 99, 82, 93, 58, 63, 55, 76,
       74, 75, 82, 77, 78, 77, 85, 59, 85, 67, 59, 93, 91, 85, 95, 82, 86,
       97, 68, 74, 88, 79, 92, 82, 98, 68, 56])

In [47]:
a3[(a3>50) & (a3>70)]

array([92, 95, 92, 93, 94, 99, 82, 93, 76, 74, 75, 82, 77, 78, 77, 85, 85,
       93, 91, 85, 95, 82, 86, 97, 74, 88, 79, 92, 82, 98])

In [48]:
a3[(a3<50) | (a3>70)]

array([18, 92, 95, 15, 92, 21, 13, 28, 93, 10, 30, 94, 99, 82, 93, 46, 34,
       31, 45, 76, 74, 75, 82, 77, 78, 77, 34, 12, 85, 19, 19, 85, 93, 47,
       91, 85, 31, 11, 42, 95, 25, 24, 33, 82, 86, 27, 41, 97, 31, 74, 29,
       88, 29, 79, 33, 92, 82, 98, 48])

In [53]:
l=list(range(100))
l
# 1,13,45,74,23,67 not possible
# if it is array then possible

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [54]:
l[[1,13,45,74,23,67]]

TypeError: list indices must be integers or slices, not list

In [57]:
al=np.array(l)
al[[1,13,45,74,23,67]]

array([ 1, 13, 45, 74, 23, 67])

In [58]:
al[[45,74,23,67,1,7,3]]

array([45, 74, 23, 67,  1,  7,  3])

In [59]:
a2

array([[11, 14, 26],
       [11, 22, 12],
       [24, 21, 16]])

In [60]:
a2[[1,2],[0,1]] #(1,0)(2,1)

array([11, 21])

In [63]:
a3[[1,2],[1,2],[1,2]] #(1,1,1)(2,2,2)
print(a3[1,1,1])
print(a3[2,2,2])

82
85


In [64]:
# statistical function in numpy
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a=np.random.randint(20,30,5)
a

array([20, 24, 24, 22, 29])

In [67]:
print(np.mean(a))
print(np.sum(a)/np.size(a))

23.8
23.8


In [68]:
# sorted a[23,34,25,27,29]
np.median(a)

24.0

In [70]:
print(np.quantile(a,0.25)) # q1
print(np.quantile(a,0.5)) # q2
print(np.quantile(a,0.75)) # q3

22.0
24.0
24.0


In [ ]:
# Logorithemic and Exponential

In [73]:
print(np.log(2)) # log with base e
print(np.log(np.exp(1)))

0.6931471805599453
1.0


In [81]:
print(np.log2(2)) 
print(np.log2(7))
print(np.log10(5))

1.0
2.807354922057604
0.6989700043360189


In [78]:
# np.log(0)
# np.log2(0)
# np.log10(0)

In [76]:
np.exp(2)

7.38905609893065

In [79]:
print(np.exp(4))#2**4

54.598150033144236


In [80]:
print(np.expm1(2)) # np.exp(2)-1
print(np.exp(2)-1)

6.38905609893065
6.38905609893065


In [82]:
np.log(0+1)

0.0

In [84]:
print(np.log1p(2)) # np.log(1+2)
print(np.log1p(0))

1.0986122886681098
0.0
