<pra>classification 
    - Binary(flight delay or on time)i/p:historic flight data
    - multiclass(iris flower(setosa,versicolor,virginica)i/p: each one having sepal length,sepal width and petal length,petal width
    - sentiment analysis(classifying the comments)
    - anomaly detection
Regression(predict the salary of the employee)
Recommender systems(amazon,flipcart,zomato,swiggy)
Reinforcement learning(cat in home get reward for positive response as food)    
NLP
    - Q & A
    - Auto completion(search engines)
    - chatbot(dominos)
Computer vision
    - object detection
    - object tracking
    - image classification
    - image tagging
Data 
    - numerical data
    - image data
    - audio data
    - video data
    - text data
    - from documents
    - satelite imagery
    - Time series data(temperature regarding)<pra>

#### What are csv and tsv files?
 Tab separated values(Tsv) and comma separated values(csv) are the two types of extensions used to load the set of data. TSV extension files are more efficient for many applications in programming languages like javascript, tensorflow etc. Also, in a TSV file rows and columns are easily distinguishable. CSV files are used more in fields like machine learning, data analysis, deep learning. Both the types of files are highly used in Data Science related fields.
    
#### What are packages available to handle csv data?
    1.Load CSV with Python Standard Library
    The Python API provides the module CSV and the function reader() that can be used to load CSV files.Once loaded, you convert the CSV data to a NumPy array and use it for machine learning.
        Ex:import csv
        import numpy
        filename = 'pima-indians-diabetes.data.csv'
        raw_data = open(filename, 'rt')
        reader = csv.reader(raw_data, delimiter=',', quoting=csv.QUOTE_NONE)
        x = list(reader)
        data = numpy.array(x).astype('float')
        print(data.shape)
        
    2.Load CSV File With NumPy
    You can load your CSV data using NumPy and the numpy.loadtxt() function.
        Ex:import numpy
        filename = 'pima-indians-diabetes.data.csv'
        raw_data = open(filename, 'rt')
        data = numpy.loadtxt(raw_data, delimiter=",")
        print(data.shape)
        (or)
        from numpy import loadtxt
        from urllib.request import urlopen
        url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv'
        raw_data = urlopen(url)
        dataset = loadtxt(raw_data, delimiter=",")
        print(dataset.shape)
        
    3.Load CSV File With Pandas
    You can load your CSV data using Pandas and the pandas.read_csv() function.
        Ex:import pandas
        filename = 'pima-indians-diabetes.data.csv'
        names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
        data = pandas.read_csv(filename, names=names)
        print(data.shape)
        
#### What is json format?
- How to handle json data?
- What are packages available for image data?
- What are the packages available for audio data?
- With all the packages above check how to read the data?
- How to display the same data?

#### QUS: Replace comma into the file sample.csv with tab and store it in a file as tsv format.
- i/p : A csv file
- o/p : Is a tsv file with same data(file handling)<pra>

In [103]:
f=open("sample.csv",'r')
n=f.read()
#print(n)
a=""
for i in n:
    n=n.replace(',','\t')
    f1=open("tsvfile.tsv",'w')
    f1.write(n)

### Lists

In [1]:
l1=[1,2,3,4]
l2=[1,2,3,4]
l1+l2

[1, 2, 3, 4, 1, 2, 3, 4]

In [2]:
o=[]
for i in range(len(l1)):
    o.append(l1[i]+l2[i])
print(o)

[2, 4, 6, 8]


In [20]:
# list comprehension
h=[l1[i]+l2[i] for i in range(len(l1))]
print(h)

[2, 4, 6, 8]


In [18]:
# print which are not multiples of 3
a=[l1[i]+l2[i] for i in range(len(l1)) if h[i]%3!=0]
print(a)

[2, 4, 8]


In [21]:
# replace the multiples of 3  with -1
out=[i if i%3!=0 else -1 for i in h]
out

[2, 4, -1, 8]

In [24]:
h.extend([2,8,9,6])
h

[2, 4, 6, 8, 2, 8, 9, 6, 2, 8, 9, 6, 2, 8, 9, 6]

In [25]:
h

[2, 4, 6, 8, 2, 8, 9, 6, 2, 8, 9, 6, 2, 8, 9, 6]

In [26]:
# replace multiples of 2 with -2
# replace multiples of 3 with -1
s=[]
for i in h:
    if i%2==0:
        s.append(-2)
    elif i%3==0:
        s.append(-1)
    else:
        s.append(i)
        
print(s)

[-2, -2, -2, -2, -2, -2, -1, -2, -2, -2, -1, -2, -2, -2, -1, -2]


In [29]:
# replace multiples of 2 with -2
# replace multiples of 3 with -1
out1=[-2 if i%2==0 else -1 if i%3==0 else i for i in h]
out1

[-2, -2, -2, -2, -2, -2, -1, -2, -2, -2, -1, -2, -2, -2, -1, -2]

### list comprehension with nested for loop

In [30]:
l1,l2

([1, 2, 3, 4], [1, 2, 3, 4])

In [33]:
a1=[(i+j) for i in l1 for j in l2]
a1

[2, 3, 4, 5, 3, 4, 5, 6, 4, 5, 6, 7, 5, 6, 7, 8]

In [37]:
l2=[[23,45],[78,96],[56,12]]
# o/p =[23,45,78,96,56,12]
num=[(i,k) for i in l1 for j in l2 for k in j]
num

[(1, 23),
 (1, 45),
 (1, 78),
 (1, 96),
 (1, 56),
 (1, 12),
 (2, 23),
 (2, 45),
 (2, 78),
 (2, 96),
 (2, 56),
 (2, 12),
 (3, 23),
 (3, 45),
 (3, 78),
 (3, 96),
 (3, 56),
 (3, 12),
 (4, 23),
 (4, 45),
 (4, 78),
 (4, 96),
 (4, 56),
 (4, 12)]

In [38]:
l2=[[23,45],[78,96],[56,12]]
# o/p =[23,45,78,96,56,12]
n1=[i for j in l2 for i in j]
n1

[23, 45, 78, 96, 56, 12]

In [48]:
# common elements in two lists using list comprehension
l3=list(range(5,20,2))
l4=list(range(1,20,2))
print(l3,l4)

[5, 7, 9, 11, 13, 15, 17, 19] [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [50]:
n=[i for i in l3 for j in l4 if i==j]
print(n)
n2=[i for j in l4 for i in l3 if i==j]
print(n2)

[5, 7, 9, 11, 13, 15, 17, 19]
[5, 7, 9, 11, 13, 15, 17, 19]


# numpy(numerical python)
- vectorized programming
- handling multidimensional data
- manipulating arrays
- we can define the datatype
- commonly used with numerical data. But you may use mixed data as well
- faster execution
- less memory
- most of the mathematical functions are available
    - linear algebra
   

In [51]:
# version of numpy
import numpy
numpy.__version__ # atribute "__" - dunder

'1.16.5'

In [52]:
# importing a package with ailas name
import numpy as np

#### converting existing data into numpy array

In [55]:
l=[7,9,0,3,4]
array_1d=np.array(l)
print(type(array_1d))

<class 'numpy.ndarray'>


In [54]:
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [56]:
t=(7,9,0,3,4)
array_1d=np.array(t)
print(type(array_1d))
print(array_1d)

<class 'numpy.ndarray'>
[7 9 0 3 4]


In [59]:
d={1:'harshi',2:"kiran"}
a=np.array(d)
print(a)
print(type(a))

{1: 'harshi', 2: 'kiran'}
<class 'numpy.ndarray'>


###### Initializing Arrays

In [60]:
np.zeros(3)

array([0., 0., 0.])

In [61]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
array_zeros=np.zeros((3,3))
print(array_zeros.dtype)
print(type(array_zeros))

float64
<class 'numpy.ndarray'>


In [65]:
array=np.zeros((5,5),dtype=int)
print(array.dtype)
print(type(array))
print(array)

int32
<class 'numpy.ndarray'>
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [66]:
array_ones=np.ones((3,3),dtype=int)
print(array_ones.dtype)
print(type(array_ones))
print(array_ones)

int32
<class 'numpy.ndarray'>
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [67]:
array_ones=np.ones((3,3),dtype=bool)
print(array_ones.dtype)
print(type(array_ones))
print(array_ones)

bool
<class 'numpy.ndarray'>
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [68]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [69]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

##### creating arrays with ina specific range

In [73]:
print(np.arange(6))
print(np.arange(1,6))
print(np.arange(1,6,2))
print(np.arange(1,6,0.5))
#print(list(range(1,6,0.5)))

[0 1 2 3 4 5]
[1 2 3 4 5]
[1 3 5]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]


In [74]:
print(np.linspace(1,5,10))

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [75]:
np.random.randint(10)

2

In [76]:
np.random.randint(10,size=(2,3))

array([[5, 7, 0],
       [4, 5, 7]])

In [78]:
multi_array=np.random.randint(1,1000,size=(10,10))
multi_array

array([[790, 125,   5,  39, 827, 418, 418, 665, 270, 920],
       [729, 591, 631, 576, 717, 525, 901,  13, 907, 923],
       [359,  85, 405, 772, 750, 152, 186, 785,   9, 550],
       [724, 698, 783, 942, 885, 325, 746, 269, 824,  47],
       [888, 538, 767, 393, 266, 840, 664, 764, 831, 849],
       [994, 305,  51, 521, 588, 685, 139, 471, 836, 353],
       [802, 378, 787, 321, 637,  68, 900, 987, 946,  34],
       [402, 556, 255, 741, 209, 265, 480, 847, 925, 430],
       [948, 657, 401,  51, 685, 607,  21, 654, 287, 748],
       [107, 523, 261, 282, 110, 685, 765, 719, 731, 196]])

In [81]:
print(array_1d.dtype) # datatype of the array
print(array_1d.shape) # shape as a tuple
print(array_1d.ndim) # no of dimensions
print(array_1d.size) # n of items in the array
print(array_1d.itemsize)# size in bytes
print(array_1d.nbytes) # itemsize * no of items
print(array_1d)

int32
(5,)
1
5
4
20
[7 9 0 3 4]


###### updating the values in an array

In [82]:
array_1d

array([7, 9, 0, 3, 4])

In [83]:
array_1d[1] = 3
array_1d

array([7, 3, 0, 3, 4])

In [84]:
array_zeros[0] = 5
array_zeros

array([[5., 5., 5.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
# check for loop with 1d and 2d arrays
for i in array_1d:
    print(i)
    break

7


In [86]:
for i in array_zeros:
    print(i)
    break

[5. 5. 5.]


### Mathematical operations

In [87]:
a= np.arange(10)
b= np.arange(10,20)
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a//b)
print(b%a)
print(a**2)

[10 12 14 16 18 20 22 24 26 28]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[0.         0.09090909 0.16666667 0.23076923 0.28571429 0.33333333
 0.375      0.41176471 0.44444444 0.47368421]
[  0  11  24  39  56  75  96 119 144 171]
[0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 2 0 4 3 2 1]
[ 0  1  4  9 16 25 36 49 64 81]


C:\Users\lenovo\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in remainder
  


In [88]:
print(a>5)
print(a==5)
print(a<5)

[False False False False False False  True  True  True  True]
[False False False False False  True False False False False]
[ True  True  True  True  True False False False False False]


In [1]:
"big">"small"

False

In [2]:
11%5

1

In [3]:
((10 >= 5*2) and (10 <= 5*2))

True

In [4]:
The counter function counts down from start to stop when start is bigger than stop, and counts up from start to stop otherwise. Fill in the blanks to make this work correctly.

TabError: inconsistent use of tabs and spaces in indentation (<ipython-input-4-ea94ad8d1960>, line 5)

In [17]:
def digits(n):
	count = 0
	if n == 0:
        print('1')
	while n!=0:
        r=n%10
        count=count+1
         n=n//10
    return count

print(digits(25))   # Should print 2
print(digits(144))  # Should print 3
print(digits(1000)) # Should print 4
print(digits(0))    # Should print 1

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 9)

In [18]:
for x in range(10):
    for y in range(x):
        print(y)

0
0
1
0
1
2
0
1
2
3
0
1
2
3
4
0
1
2
3
4
5
0
1
2
3
4
5
6
0
1
2
3
4
5
6
7
0
1
2
3
4
5
6
7
8
