In [1]:
# importing packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
# reading data
df=pd.read_csv('BostonHousing.csv')
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [6]:
df.corr()

crim        zn     indus      chas       nox        rm       age  \
crim     1.000000 -0.200469  0.406583 -0.055892  0.420972 -0.219247  0.352734   
zn      -0.200469  1.000000 -0.533828 -0.042697 -0.516604  0.311991 -0.569537   
indus    0.406583 -0.533828  1.000000  0.062938  0.763651 -0.391676  0.644779   
chas    -0.055892 -0.042697  0.062938  1.000000  0.091203  0.091251  0.086518   
nox      0.420972 -0.516604  0.763651  0.091203  1.000000 -0.302188  0.731470   
rm      -0.219247  0.311991 -0.391676  0.091251 -0.302188  1.000000 -0.240265   
age      0.352734 -0.569537  0.644779  0.086518  0.731470 -0.240265  1.000000   
dis     -0.379670  0.664408 -0.708027 -0.099176 -0.769230  0.205246 -0.747881   
rad      0.625505 -0.311948  0.595129 -0.007368  0.611441 -0.209847  0.456022   
tax      0.582764 -0.314563  0.720760 -0.035587  0.668023 -0.292048  0.506456   
ptratio  0.289946 -0.391679  0.383248 -0.121515  0.188933 -0.355501  0.261515   
b       -0.385064  0.175520 -0.356977  0.048788 -0.380051  0.128069 -0.273534   
lstat    0.455621 -0.412995  0.603800 -0.053929  0.590879 -0.613808  0.602339   
medv    -0.388305  0.360445 -0.483725  0.175260 -0.427321  0.695360 -0.376955   

              dis       rad       tax   ptratio         b     lstat      medv  
crim    -0.379670  0.625505  0.582764  0.289946 -0.385064  0.455621 -0.388305  
zn       0.664408 -0.311948 -0.314563 -0.391679  0.175520 -0.412995  0.360445  
indus   -0.708027  0.595129  0.720760  0.383248 -0.356977  0.603800 -0.483725  
chas    -0.099176 -0.007368 -0.035587 -0.121515  0.048788 -0.053929  0.175260  
nox     -0.769230  0.611441  0.668023  0.188933 -0.380051  0.590879 -0.427321  
rm       0.205246 -0.209847 -0.292048 -0.355501  0.128069 -0.613808  0.695360  
age     -0.747881  0.456022  0.506456  0.261515 -0.273534  0.602339 -0.376955  
dis      1.000000 -0.494588 -0.534432 -0.232471  0.291512 -0.496996  0.249929  
rad     -0.494588  1.000000  0.910228  0.464741 -0.444413  0.488676 -0.381626  
tax     -0.534432  0.910228  1.000000  0.460853 -0.441808  0.543993 -0.468536  
ptratio -0.232471  0.464741  0.460853  1.000000 -0.177383  0.374044 -0.507787  
b        0.291512 -0.444413 -0.441808 -0.177383  1.000000 -0.366087  0.333461  
lstat   -0.496996  0.488676  0.543993  0.374044 -0.366087  1.000000 -0.737663  
medv     0.249929 -0.381626 -0.468536 -0.507787  0.333461 -0.737663  1.000000

##### taking data 'rm' and 'medv'

In [7]:
x=df[['rm']]
y=df['medv']

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


In [43]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
linear=LinearRegression()
linear.fit(x_train,y_train)
y_pred=linear.predict(x_test)

In [44]:
y_pred

array([20.231239  , 21.70661225, 19.7036813 , 17.64710041, 17.30731748,
       19.90039773, 18.79163238, 19.04199875, 26.32050676, 17.41461735,
       26.55298982, 31.79280026, 25.79294906, 36.16527006, 23.95096791,
       18.59491595, 19.39072333, 21.92121199, 23.42341021, 21.94803696,
       38.2933842 , 40.5913898 , 17.89746678, 17.42355901, 27.0447809 ,
       21.07175467, 28.83311211, 18.87210728, 20.18653072, 22.04639518,
       20.9018632 , 23.53071008, 29.13712842,  7.7844538 , 23.90625963,
       22.10004511, 25.57834931, 23.41446855, 23.58436002, 18.58597429,
       11.94232385, 20.25806397, 19.74838958, 27.75117173, 31.5603172 ,
       22.84220256, 20.07923085, 22.12687008, 16.71716818, 24.61265046,
       24.6663004 , 25.12232485, 33.19664026, 19.02411544, 20.62467187,
       33.64372306, 20.91080486, 23.66483492, 20.32065556, 20.50843034,
       19.37284002, 26.74970625, 14.18667952, 19.07776537, 20.95551314,
       29.05665351, 21.20587951, 22.84220256, 21.42047925, 21.60

In [45]:
r2_score(y_test,y_pred)

-3.047487853019075

In [47]:
mean_squared_error(y_pred,y_test)

194.3815795609157

##### taking data 'lstat' and 'medv'

In [25]:
x_data=df[['lstat']]
y_data=df['medv']

In [26]:
x_train_data,x_test_data,y_train_data,y_test_data=train_test_split(x_data,y_data,test_size=0.2)

In [27]:
lr=LinearRegression()
lr.fit(x_train_data,y_train_data)
y_prod=lr.predict(x_test_data)

In [28]:
y_prod

array([18.47372955, 18.15088226, 25.91820819, 22.07252726, 19.08144209,
        9.47198752, 17.33426854,  8.16160736, 31.60601776, 17.41972811,
       30.09623192, 25.65233395, 18.31230591, 18.66363972, 28.35855387,
       24.51287294, 29.31760022, 24.81672921, 22.17697785, 21.63573387,
       25.24402709, 17.84702599, 25.80426209, 30.06774539, 31.15023336,
       22.21495989, 29.77338463, 10.43103388, 24.63631455, 25.09209895,
       22.0060587 , 12.63399184, 29.99178132, 24.14254811, 11.39957574,
       22.07252726, 21.17045396, 28.60543709, 28.74786971, 25.73779353,
       11.67494549, 25.9277037 , 18.96749599, 21.78766201, 31.40661209,
       29.49801488, 24.68379209, 20.15443455, 28.17813921, 17.4102326 ,
       11.2381521 ,  4.18298931, 26.23155997, 16.78352904, 25.74728904,
       12.14972091, 29.14668107, 30.83688158, 21.17994947, 21.00903031,
       27.77932785, 30.20068251, 30.98880971,  5.30345931, 14.12478667,
       20.60072345, 28.27309429, 20.91407523, 24.4653954 , 26.54

In [32]:
from sklearn.metrics import r2_score
r2_score(y_test_data,y_prod)

0.5575677623733868

In [48]:
mean_squared_error(y_prod,y_test_data)

34.49242378633499

##### taking data 'rm' and 'lstat'

In [33]:
x1=df[['rm']]
y1=df['lstat']

In [39]:
x_train1,x_test1,y_train1,y_test1=train_test_split(x1,y1,test_size=0.2)

In [40]:
Linear_Regression=LinearRegression()
Linear_Regression.fit(x_train1,y_train1)
y_predict=Linear_Regression.predict(x_test1)

In [41]:
y_predict

array([ 6.80185471, 15.16511775, 13.05463914,  8.14548239, 12.22224541,
       14.21474695, 15.49283181,  3.6033654 ,  6.78219187, 11.57992583,
       15.15856346, 26.89072712, 15.37485475, 10.98348623,  1.12584704,
        5.7859411 , 21.00498245, 11.53404586,  9.27281879, 13.18572477,
       16.24657417, 13.10051911, 13.30370184, 14.91605505, 13.61830734,
       13.17917049, 15.66979741, 16.89544803, 12.59583945,  6.08088376,
       16.03683717, 14.02467279, 15.62391744, 11.47505733, 16.56773396,
       11.14734326,  5.94979813, 12.03217125, 12.34022247,  9.36457873,
       11.08835473, 13.97879282, 15.50594038,  9.04341894, 15.85331729,
       17.35424772, 14.25407263, 16.34488839, 12.49097094, 11.92730275,
       11.3439717 , 16.11548854,  1.3159212 ,  9.56120717, 15.77466591,
       15.2503234 , 13.22505046, 12.8580107 , 17.51155048,  8.92544188,
       15.54526607, 13.18572477, 12.74003364, 11.95351987, 10.00034402,
        9.22693882, 15.51249466, 30.67254748,  6.96571175,  9.44

In [42]:
r2_score(y_test1,y_predict)

0.19842851498524983

In [49]:
mean_squared_error(y_test1,y_predict)

31.0718257242641

In [50]:
x2=df[['crim']]
y2=df['zn']

In [51]:
x_trin,x_tst,y_trin,y_tst=train_test_split(x2,y2,test_size=0.2)

In [52]:
l=LinearRegression()
l.fit(x_trin,y_trin)
y_=l.predict(x_tst)

In [53]:
y_

array([ 13.61774783,  12.91479242,  13.71517679,  13.81271317,
        13.74412619,  13.79766259,  13.79565743,  -1.12550551,
         6.18124908,   9.32999017,   6.68922124,  13.75119794,
        12.99298743,  13.72043435,  11.37608794,  13.09110268,
        13.77172092, -39.27718648,  13.75524405,   7.71453487,
        13.50255296,  12.40183721,  10.94955723,  13.49303445,
        13.71683582,  13.75311954,  13.45635089,   5.26735274,
        13.78786956,  13.78924214,  10.93550922,  13.72655723,
        12.44043045,  13.80824932,  13.74517054,  13.81234317,
        11.0481678 ,   8.61939011,  10.5741818 ,  13.78680731,
         4.76397573,  13.76959641,  13.50083426,  13.73120011,
         5.21537392,  13.07426775,  13.69168785,  13.7579713 ,
        13.79428486,  13.75819807,  13.79899339,  13.79132487,
         9.1430156 ,  13.80250241,  13.79919032,  13.78012943,
        13.42943052,  13.75264809,  13.60112773,   8.25396287,
        13.74337426,  12.18974452,  13.76315127,  13.79

In [54]:
r2_score(y_tst,y_)

0.01969776085474828

In [55]:
mean_squared_error(y_tst,y_)

429.14834060249007